### ISSUE TITLE
Längen für Aluprofile

### ISSUE THREAD

**Issue by Pteppic1** [MakeMagazinDE/Wabentisch#1]
Hallo,

ich habe weder in der Zeitschrift, noch im zugehörigen Forum oder hier die Zuschnittlängen für das Aluprofil gefunden.
Ich hoffe, diese müssen nicht durch Ausprobieren gefunden werden

Danke

**Comment by MakeMagazinDE** [comment]
Sehr geehrter Leser,
die Maße der Aluprofile sind im Artikel unter "Mechanik zusammenbauen" aufgeführt.
Mit freundlichen Grüßen
Heinz Behling

**Comment by Pteppic1** [comment]
Hatte ich nicht gesehen, danke für die Klarstellung
